### ISSUE TITLE
wildcard selector disrupts own styles

### ISSUE THREAD

**Issue by ChristianOsswald** [eibiflo/cf_cookiemanager#42]
In iframemanager.scss there is "div[data-service] *" defined, which disrupts styling of div content.

**Comment by eibiflo** [comment]
Hello @ChristianOsswald 

do you have a specific example?
You're probably referring to this line: https://github.com/eibiflo/cf_cookiemanager/blob/main/Resources/Public/Scss/thirdparty/iframemanager.scss#L1

Where exactly is the problem, and what is your proposed solution?

**Comment by ChristianOsswald** [comment]
Actually every element inside the div gets those CSS properties. Could we limit it to the needed elements/classes?

I got the issue, that my included google map got styling issues because of background and font-size properties overridden.

**Comment by eibiflo** [comment]
Thanks for the info, I can of course add CSS classes, that wouldn’t be a problem.
I'm just trying to find the source, as far as I know, CSS is not implemented in the iframe.

I quickly recreated the example and couldn’t reproduce the issue, maybe I'm doing something wrong, but I haven’t heard of this problem before. Even when I check the computed styles, the style is not displayed, which makes things interesting.

![image](https://github.com/user-attachments/assets/93bd3aeb-9084-4d24-ad97-7a1dea104896)

The iframe is independent and shouldn’t inherit anything, as it operates in the "parent browsing context"
(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe)

Which browser are you using, and which version of the cookie manager is being used?
Do you have a screenshot where this can be traced, so I can debug it locally or maybe your Website is Public so write me a PM in T3-slack with the Domain?

**Comment by ChristianOsswald** [comment]
I am not using the embed iframe version. Maybe that's the problem.

**Comment by eibiflo** [comment]
Oh yes, that makes sense. I'll take a look at it myself and get back to you as soon as I know more. 
That was already a great tip, thanks!

**Comment by eibiflo** [comment]
I  tested this with OpenStreetMap since I didn’t have an API key handy for Google Maps, but I have another question:

If you remove the wildcard and leave only div[data-service], do the styles still inherit?
Dose use font-size: inherit; work to get the original font-size?

For Example:
```css
div[data-service], div[data-service] :after, div[data-service] :before {
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  float: none;
  font-style: inherit;
  font-variant: normal;
  font-weight: inherit;
  font-family: inherit;
  line-height: inherit;
  font-size: inherit;
  margin: 0;
  padding: 0;
  text-transform: none;
  letter-spacing: unset;
  color: inherit;
  background: inherit;
  border: none;
  box-shadow: none;
  text-decoration: none;
  text-align: left
}
```

If I add a class, I assume that only auto-blocked elements will have that class, so you would need to style the popup yourself unless you use this. The problem, however, is that the styles would still inherit otherwise.

The Example  "font-size: inherit;" would solve this at least for the font-size Can you confirm?
