### ISSUE TITLE
Database-initialisation failed if SitePageId is not "1"

### ISSUE THREAD

**Issue by jacques2017** [eibiflo/cf_cookiemanager#66]
Hi,

when the Rootpage-Id is not "1" the initialisation of the database failed.

You can find the "bug" here:

https://github.com/eibiflo/cf_cookiemanager/blob/567cbf59094ab3eeabd6c69cf25e85919c700283/Classes/Service/InsertService.php#L31C1-L31C83

If I set the page-id to the page-id of my rootpage (line 31)  the database-initialisation works.

Greetings
Jacques

**Comment by eibiflo** [comment]
Thank you for the description.

When I try to reproduce this, the services are not displayed in the backend. 
Even when I set the root page ID explicitly in https://github.com/eibiflo/cf_cookiemanager/blob/567cbf59094ab3eeabd6c69cf25e85919c700283/Classes/Service/InsertService.php#L31C1-L31C83

 Did that work for you?

Are you on  Typo3 13 or 12 with the latest extension version? 
Can you share me your siteconfig or some insights, whats your Main Language ID and the Overlay?   
I have this as Example in V13 and it dose not even display in the Backend after Installation. 


```yaml
base: 'https://typo13.ddev.site/autogenerated-9'
dependencies:
  - bootstrap-package/full
  - CodingFreaks/cf-cookiemanager
languages:
  -
    title: German
    enabled: true
    languageId: 2
    base: /
    locale: de_AT.utf8
    navigationTitle: ''
    flag: global
    hreflang: de-AT
    websiteTitle: ''
    fallbackType: strict
    fallbacks: '0'
  -
    title: Englisch
    enabled: true
    locale: en_US.utf8
    hreflang: en-US
    base: /en
    websiteTitle: ''
    navigationTitle: ''
    fallbackType: strict
    fallbacks: '1'
    flag: global
    languageId: 3
rootPageId: 9
websiteTitle: ''

```

At the first look, it looks like a really dumb mistake, so I don’t quite understand how it’s showing up for you. If you change the variable, it should work for me as well, but it didn´t. 


Thanks!
